server:
  port: 9092


spring:
  rabbitmq:
    host: localhost #34.155.175.192
    port: 5672 #rest portu
    username: java11
    password: 123
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserProfileDB
      username: defaultUSer
      password: bilge!*123

usermicroservice:
  redis:
    host: localhost
    port: 6379
